name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        type: string
        description: Image tag to use
        required: true
      environment:
        type: environment
        description: Environment to deploy to
        required: true

jobs:

  deploy:
    name: Deploy via CDK
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment || 'brianrook-aws' }}
    env:
      IMAGE_TAG: ${{github.event.inputs.image_tag}}

    steps:
      - name: Echo image tag
        run: |
          echo "image tag: $IMAGE_TAG"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'SlackHelloworldStack'
          cdk_args: "--require-approval never"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
